rvm:
  - 2.2

before_script:
  - psql -c 'create database sendonfly_social_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

notifications:
  hipchat: <%= ENV['HIPCHAT_TOKEN'] %>@1335283

addons:
  code_climate:
    repo_token: <%= ENV['CODECLIMATE_TOKEN'] %>
  postgresql: "9.3"