rvm:
  - 2.2

before_script:
  - psql -c 'create database sendonfly_social_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

notifications:
  hipchat: 3bf913639d5695d46817576a7f94dd@1335283

addons:
  code_climate:
    repo_token: 1e94e66ad5e8460f0b1fb3eb897a6475911f6ceb585226d347495ee0f71f8951
  postgresql: "9.3"